function createCard({ picture, titleText, link }) {
  const card = document.createElement('article');
  card.className = 'dell-cards-card';

  if (picture) {
    card.append(picture.cloneNode(true));
  }

  const body = document.createElement('div');
  body.className = 'dell-cards-card-body';

  if (titleText) {
    const title = document.createElement('h3');
    title.textContent = titleText;
    body.append(title);
  }

  const spacer = document.createElement('div');
  spacer.className = 'dell-cards-spacer';
  body.append(spacer);

  if (link) {
    body.append(link.cloneNode(true));
  }

  card.append(body);

  return card;
}

export default function decorate(block) {
  const rows = [...block.children];

  // Eyebrow already exists
  const eyebrow = rows[0];

  // Heading already exists
  const heading = rows[1];

  // Cards container generated by UE
  const cardsRow = rows[2];

  // Footer container
  const footerRow = rows[3];

  // Create new cards wrapper
  const cardsWrapper = document.createElement('div');
  cardsWrapper.className = 'dell-cards-list';

  // Find all headlines
  const headlines = cardsRow.querySelectorAll(
    '[data-aue-prop$="Headline"]',
  );

  headlines.forEach((headline) => {
    const prop = headline.dataset.aueProp.replace('Headline', '');

    const picture = cardsRow.querySelector(
      `[data-aue-prop="${prop}Image"]`,
    )?.closest('picture');

    const link = cardsRow.querySelector(
      `[data-aue-prop="${prop}LinkText"]`,
    )?.closest('a');

    const card = createCard({
      picture,
      titleText: headline.textContent.trim(),
      link,
    });

    cardsWrapper.append(card);
  });

  // Footer links
  const footerLinks = document.createElement('div');
  footerLinks.className = 'footer-links';

  footerRow.querySelectorAll('a').forEach((link) => {
    footerLinks.append(link.cloneNode(true));
  });

  // CLEAR BLOCK
  block.innerHTML = '';

  // REBUILD CLEAN STRUCTURE
  if (eyebrow) block.append(eyebrow);
  if (heading) block.append(heading);

  block.append(cardsWrapper);
  block.append(footerLinks);
}